// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

class TestStruct extends ffi.Struct {
  @ffi.Int()
  external int testBoolean;

  @ffi.Int()
  external int testInt;

  @ffi.Float()
  external double testFloat;

  @ffi.Double()
  external double testDouble;

  external ffi.Pointer<ffi.Char> testStr;

  @ffi.Int()
  external int operator1;
}
